Repository Owlvernyte/cotuong-frontend, pull requests merged in 2023-10, with the labels that each got.

#27 Routes refactor
  app/(basic)/competitions/page.tsx
  app/(basic)/contact/page.tsx
  app/(basic)/histories/[id]/page.tsx
  app/(basic)/histories/page.tsx
  app/(basic)/rooms/[id]/page.tsx
  app/(basic)/rooms/page.tsx
  app/(basic)/settings/account/page.tsx
  app/(basic)/settings/page.tsx
  app/(basic)/users/[id]/page.tsx
  features/user/useUser.ts
Labels: enhancement

#28 [I] Refactor and optimize code
  app/(basic)/leaderboard/page.tsx
  app/(basic)/page.tsx
  app/(basic)/settings/account/page.tsx
  app/(basic)/signin/page.tsx
  app/(basic)/signup/page.tsx
  components/account/forms/ChangePasswordForm.tsx
  components/account/forms/UpdateEmailForm.tsx
  components/account/forms/UpdateUsernameForm.tsx
  components/auth/AuthCard.tsx
  components/auth/signin/SignInForm.tsx
  components/auth/signup/SignUpForm.tsx
  components/layouts/Footer.tsx
  components/layouts/Header.tsx
  components/leaderboard/personal-achievements/CardTitle.tsx
  components/ui/IconButton.tsx
  components/ui/Title.tsx
  public/icons/primary/Mail.svg
  public/icons/primary/check.svg
  public/icons/secondary/Pass_word.svg
Labels: enhancement

#32 [HOTFIX] fix api route
  lib/configs/api.config.ts
Labels: bug

#33 Implement chat
  .vscode/settings.json
  app/(basic)/rooms/[id]/Disconnected.tsx
  app/(basic)/rooms/[id]/LeftArea/ChatBox.tsx
  app/(basic)/rooms/[id]/LeftArea/ChatBubble.tsx
  app/(basic)/rooms/[id]/LeftArea/MenuBox.tsx
  app/(basic)/rooms/[id]/LeftArea/MenuBoxTitle.tsx
  app/(basic)/rooms/[id]/RightArea/PlayerArea.tsx
  app/(basic)/rooms/[id]/WaitingContainer.tsx
  app/(basic)/rooms/[id]/page.tsx
  components/rooms/ButtonsMenuList.tsx
  components/rooms/CreateRoomButton.tsx
  features/room/room.service.ts
  features/room/room.types.ts
  features/room/useGetRoomById.ts
  lib/hooks/useSignalR.ts
Labels: enhancement

#35 [FIX] real fix player area
  app/(basic)/rooms/[id]/page.tsx
Labels: bug

#38 added register and error handler
  components/auth/signup/SignUpForm.tsx
  features/user/useLogin.ts
  features/user/useRegister.ts
  features/user/user.service.ts
  features/user/user.types.ts
  lib/@types/global.d.ts
Labels: enhancement

#39 [PIECE] General Logic - FrontEnd
  app/(basic)/rooms/[id]/page.tsx
  lib/game/QuanCo/Piece.ts
  lib/game/QuanCo/collections/Chariot.ts
  lib/game/QuanCo/collections/General.ts
Labels: enhancement

#43 [Masterpiece] Piece cant move when between generals
  lib/game/Board.ts
Labels: enhancement

#42 Logic(soldier): Prevent soldier move backward
  components/layouts/Providers.tsx
  lib/game/QuanCo/collections/Soldier.ts
Labels: enhancement

#41 Added elephant logic to Pieces
  lib/game/QuanCo/collections/Elephant.ts
Labels: enhancement

#47 [FEATURE] Game Room Updates
  app/(basic)/rooms/[id]/Game.tsx
  app/(basic)/rooms/[id]/page.tsx
  app/globals.css
  components/auth/AuthHeaderArea.tsx
  components/rooms/ButtonsMenuList.tsx
  components/rooms/CreateRoomButton.tsx
  components/rooms/FindRoomButton.tsx
  lib/constants/storeKeys.ts
  lib/game/QuanCo/Piece.ts
  lib/zustand/store.ts
  middleware.ts
  tailwind.config.ts
Labels: enhancement

#40 [FEATURE] Pieces Logic
  app/(basic)/rooms/[id]/Game.tsx
  app/(basic)/rooms/[id]/LeftArea/MenuBox.tsx
  app/(basic)/rooms/[id]/Piece.tsx
  app/(basic)/rooms/[id]/RightArea/PlayerArea.tsx
  components/layouts/Providers.tsx
  lib/game/Board.ts
  lib/game/QuanCo/Piece.ts
  lib/game/QuanCo/collections/Advisor.ts
  lib/game/QuanCo/collections/Cannon.ts
  lib/game/QuanCo/collections/Chariot.ts
  lib/game/QuanCo/collections/Elephant.ts
  lib/game/QuanCo/collections/General.ts
  lib/game/QuanCo/collections/Horse.ts
  lib/game/QuanCo/collections/Soldier.ts
  public/sfx/msg.mp3
  public/sfx/won.mp3
Labels: enhancement

#48 15 feature help contact page
  app/(basic)/contact/page.tsx
  components/contact/ContactForm.tsx
  components/contact/HelpList.tsx
  public/assets/mail_google.svg
Labels: enhancement

#50 Match detail page UI
  app/(basic)/matches/[id]/MatchDetail.tsx
  app/(basic)/matches/[id]/MatchPlayer.tsx
  app/(basic)/matches/[id]/page.tsx
  components/layouts/Header.tsx
  components/layouts/NavLinks.tsx
  features/match/match.service.ts
  features/match/match.types.ts
  features/match/useGetMatchById.ts
  features/match/useGetMatches.ts
Labels: enhancement

#52 [FEAT] Matches page
  app/(basic)/histories/[id]/page.tsx
  app/(basic)/histories/page.tsx
  app/(basic)/matches/[id]/MatchDetail.tsx
  app/(basic)/matches/[id]/MatchPlayer.tsx
  app/(basic)/matches/[id]/page.tsx
  app/(basic)/matches/page.tsx
  components/layouts/Header.tsx
  components/layouts/NavLinks.tsx
  components/matches/MatchesTable.tsx
  features/match/match.service.ts
  features/match/match.types.ts
  features/match/useGetMatchById.ts
  features/match/useGetMatches.ts
  public/assets/icons/primary/Add_Friend.svg
  public/assets/icons/primary/Result.svg
Labels: enhancement

#30 [Feature] User Information Page
  app/(basic)/users/[id]/page.tsx
  components/player/PlayerInformation.tsx
  components/ui/Button.tsx
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#53 [FIX] LeaderBoard - Change Image Src
  components/leaderboard/personal-achievements/Ranking.tsx
Labels: enhancement

#54 fixed signalr issue thanks to @BuiDatShiro
  package-lock.json
  package.json
  yarn.lock
Labels: bug

#55 feat: Add flip board
  app/(basic)/rooms/[id]/Game.tsx
Labels: enhancement

#56 turned game table with viewer side
  app/(basic)/rooms/[id]/Game.tsx
Labels: enhancement

#57 prevent same destination
  app/(basic)/rooms/[id]/Game.tsx
  public/sfx/piece-move.mp3
Labels: enhancement

#58 update board events
  app/(basic)/rooms/[id]/Game.tsx
  components/rooms/FindRoomButton.tsx
  lib/hooks/useSignalR.ts
Labels: enhancement

#61 Vietsub
  app/(basic)/rooms/[id]/Game.tsx
  app/(basic)/rooms/[id]/LeftArea/ChatBox.tsx
  app/(basic)/rooms/[id]/RightArea/PlayerArea.tsx
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question, wontfix

#62 added "REAL" display name
  app/(basic)/settings/account/page.tsx
  app/(basic)/users/[id]/page.tsx
  components/account/forms/ChangePasswordForm.tsx
  components/account/forms/UpdateEmailForm.tsx
  components/account/forms/UpdateUsernameForm.tsx
Labels: enhancement
